import { mkdir, writeFile } from "node:fs/promises";

const demo = process.argv.includes("--demo");
const user = process.env.GITHUB_USER || "Kaze-coder";
const token = process.env.GITHUB_TOKEN;
const out = new URL("../profile/", import.meta.url);

const escapeXml = (value) => String(value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;" })[char]);

async function fetchProfile() {
  if (!token) throw new Error("GITHUB_TOKEN is required unless --demo is used");
  const now = new Date();
  const from = new Date(Date.UTC(now.getUTCFullYear(), 0, 1)).toISOString();
  const query = `query($login:String!,$from:DateTime!){user(login:$login){followers{totalCount}repositories(first:100,ownerAffiliations:OWNER){nodes{isFork stargazerCount primaryLanguage{name color}}}contributionsCollection(from:$from){contributionCalendar{totalContributions weeks{contributionDays{contributionCount}}}}}}`;
  const response = await fetch("https://api.github.com/graphql", {
    method: "POST",
    headers: { authorization: `Bearer ${token}`, "content-type": "application/json", "user-agent": "kaze-profile-stats" },
    body: JSON.stringify({ query, variables: { login: user, from } }),
  });
  if (!response.ok) throw new Error(`GitHub API returned ${response.status}`);
  const payload = await response.json();
  if (payload.errors?.length) throw new Error(payload.errors.map(({ message }) => message).join("; "));
  const profile = payload.data?.user;
  if (!profile) throw new Error(`GitHub user not found: ${user}`);
  const repos = profile.repositories.nodes.filter((repo) => !repo.isFork);
  // Repository counts keep the language signal stable without cloning source code.
  const languages = new Map();
  for (const repo of repos) {
    if (!repo.primaryLanguage) continue;
    const current = languages.get(repo.primaryLanguage.name) || { count: 0, color: repo.primaryLanguage.color || "#858b7d" };
    current.count += 1;
    languages.set(repo.primaryLanguage.name, current);
  }
  return {
    user,
    repositories: repos.length,
    stars: repos.reduce((sum, repo) => sum + repo.stargazerCount, 0),
    followers: profile.followers.totalCount,
    contributions: profile.contributionsCollection.contributionCalendar.totalContributions,
    weeklyContributions: profile.contributionsCollection.contributionCalendar.weeks.map(({ contributionDays }) => contributionDays.reduce((sum, { contributionCount }) => sum + contributionCount, 0)),
    languages: [...languages].map(([name, value]) => ({ name, ...value })).sort((a, b) => b.count - a.count).slice(0, 5),
    generatedAt: now.toISOString(),
  };
}

const stats = demo ? {
  user,
  repositories: 13,
  stars: 46,
  followers: 6,
  contributions: 384,
  weeklyContributions: Array.from({ length: 40 }, (_, week) => (week * 7 + 11) % 19),
  languages: [
    { name: "JavaScript", count: 5, color: "#f1e05a" },
    { name: "TypeScript", count: 2, color: "#3178c6" },
    { name: "HTML", count: 1, color: "#e34c26" },
    { name: "PHP", count: 1, color: "#4f5d95" },
    { name: "GDScript", count: 1, color: "#355570" },
  ],
  generatedAt: "2026-09-27T00:00:00.000Z",
} : await fetchProfile();

const total = Math.max(1, stats.languages.reduce((sum, language) => sum + language.count, 0));
const bars = stats.languages.map((language, index) => {
  const width = Math.round((language.count / total) * 400);
  const y = 150 + index * 17;
  return `<text x="564" y="${y + 8}" fill="#858b7d" font-size="10">${escapeXml(language.name)}</text><rect x="680" y="${y}" width="${width}" height="8" rx="4" fill="${escapeXml(language.color)}"/>`;
}).join("");

const metric = (x, label, value) => `<text x="${x}" y="83" fill="#858b7d" font-size="10" letter-spacing="1.5">${label}</text><text x="${x}" y="126" fill="#eee9dd" font-size="34" font-weight="800">${value}</text>`;
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1012 250" role="img" aria-label="GitHub statistics for ${escapeXml(user)}">
<style>text{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace}</style>
<rect width="1012" height="250" rx="14" fill="#10130f" stroke="#2b3028"/>
<text x="34" y="38" fill="#d8f06a" font-size="11" font-weight="700" letter-spacing="2">GITHUB TELEMETRY / ${escapeXml(user.toUpperCase())}</text>
${metric(34, "REPOSITORIES", stats.repositories)}${metric(170, "STARS", stats.stars)}${metric(282, "FOLLOWERS", stats.followers)}${metric(410, "CONTRIBUTIONS", stats.contributions)}
<path d="M534 58v158" stroke="#2b3028"/>
<text x="564" y="83" fill="#eea84b" font-size="10" font-weight="700" letter-spacing="1.5">PRIMARY LANGUAGE SIGNAL</text>${bars}
<text x="34" y="222" fill="#62685d" font-size="9">UPDATED ${escapeXml(stats.generatedAt.slice(0, 10))} / GENERATED BY CAT.OS</text>
</svg>\n`;

const weeklyMax = Math.max(1, ...stats.weeklyContributions);
const graphPoints = stats.weeklyContributions.map((value, index) => {
  const x = 42 + (index / Math.max(1, stats.weeklyContributions.length - 1)) * 928;
  const y = 218 - (value / weeklyMax) * 142;
  return `${x.toFixed(1)},${y.toFixed(1)}`;
});
const graphSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1012 270" role="img" aria-label="Weekly contribution activity for ${escapeXml(user)}">
<style>text{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace}</style>
<defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#d8f06a" stop-opacity=".28"/><stop offset="1" stop-color="#d8f06a" stop-opacity="0"/></linearGradient></defs>
<rect width="1012" height="270" rx="14" fill="#10130f" stroke="#2b3028"/>
<text x="34" y="38" fill="#d8f06a" font-size="11" font-weight="700" letter-spacing="2">ACTIVITY SIGNAL / WEEKLY CONTRIBUTIONS</text>
<text x="978" y="38" text-anchor="end" fill="#858b7d" font-size="9">${stats.contributions} TOTAL / ${stats.weeklyContributions.length} WEEKS</text>
<path d="M42 82H970M42 128H970M42 174H970M42 220H970" stroke="#2b3028"/>
<polygon points="42,220 ${graphPoints.join(" ")} 970,220" fill="url(#area)"/>
<polyline points="${graphPoints.join(" ")}" fill="none" stroke="#eea84b" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>
<circle cx="${graphPoints.at(-1).split(",")[0]}" cy="${graphPoints.at(-1).split(",")[1]}" r="5" fill="#d8f06a"/>
<text x="42" y="247" fill="#62685d" font-size="9">OLDEST</text><text x="970" y="247" text-anchor="end" fill="#62685d" font-size="9">LATEST</text>
</svg>\n`;

await mkdir(out, { recursive: true });
await Promise.all([
  writeFile(new URL("stats.json", out), `${JSON.stringify(stats, null, 2)}\n`),
  writeFile(new URL("stats.svg", out), svg),
  writeFile(new URL("activity-graph.svg", out), graphSvg),
]);
console.log(`Generated stats for ${user}.`);
